#!/usr/bin/python

def PrintAccountInfo(acinfo, keys, color, pfull = False, batch = False):
    fgnescape = '\x1b[0;38;5;{0}m'
    bgnescape = '\x1b[0;48;5;{0}m'
    fgbescape = '\x1b[1;38;5;{0}m'

    ac_color = ''
    user_color = ''
    pass_color = ''
    txtreset = ''

    if color:
        ac_color = fgbescape.format(7)
        user_color = fgnescape.format(6)
        pass_color = fgnescape.format(9)
        txtreset = '\x1b[0m'

    for ac in sorted(acinfo.keys()):
        if batch:
            if 'acname' in keys:
                print(ac)
            for (k, v) in acinfo[ac].items():
                if k in keys:
                    print(v)
        else:
            if ('user' in acinfo[ac]) and ('user' in keys):
                print("{0}{1} - {2}{3}".format(ac_color, ac, user_color, acinfo[ac]['user']))
            else: print("{0}{1}".format(ac_color, ac))

            if ('pass' in keys) and ('pass' in acinfo[ac]):
                print("\t{0}{1}".format(pass_color, acinfo[ac]['pass']))

            print(txtreset, end='')

            minlen = 0
            if 'user' in keys: minlen += 1
            if 'pass' in keys: minlen += 1

            if len(keys) > minlen:
                for (k, v) in acinfo[ac].items():
                    if (k not in ['user', 'pass']) and (k in keys):
                        print("\t{0}: {1}".format(k, v))
            elif pfull:
                for (k, v) in acinfo[ac].items():
                    if k not in ['user', 'pass']:
                        print("\t{0}: {1}".format(k, v))

def CreateEntry(acname = None):
    if not(acname): acname = input("Account name: ")

    acinfo = {}

    usr = input("{0}: User - leave blank to remove field: ".format(acname))

    from getpass import getpass as gp
    pwrd = gp("{0}: Password - leave blank to remove field (typed letters do not appear): ".format(acname))

    if usr.strip():
        acinfo['user'] = usr
    if pwrd.strip():
        acinfo['pass'] = pwrd

    response = input("Would you like to add additional fields to the entry? [N/y] ")
    if response != '' and response.lower()[0] == 'y':
        print("Please type field and hit enter - blank field cancels.")
        field = input("{0}: Field: ".format(acname))
        while(field):
            if field in ["username", "u"]: field = "user"
            if field in ["password", "p", "pass"]:
                from getpass import getpass as gp
                field = "pass"
                acinfo[field] = gp("{0}: ".format(field))
            else:
                acinfo[field] = input("{0}: ".format(field))
            field = input("{0}: Field: ".format(acname))
    return (acname, acinfo)

def GetOptions():
    """Gets options from user through configuration file and commandline."""
    from optparse import OptionParser

    parser = OptionParser()

    parser.add_option("-b", "--batch", dest="batch_mode",
            action="store_true", default=False,
            help="Option to print in batch mode: no colors, no copying, no field labels, no formatting.")

    parser.add_option("-u", "--users", dest="print_users",
            action="store_true", default=False,
            help="Add users to printed fields.")

    parser.add_option("-p", "--passwords", dest="print_pass",
            action="store_true", default=False,
            help="Add passwords to printed fields.")

    parser.add_option("-n", "--no-copy", dest="no_xclip",
            action="count", default = 0,
            help="Don't copy alphabetically first matching password to clipboard.")

    parser.add_option("--copy", dest="xclip",
            action="count", default = 0,
            help="Copy alphabetically first matching password to clipboard [default].")

    parser.add_option("-l", "--login", dest="login",
            action="store_true", default=False,
            help="Just login, don't show anything.")

    parser.add_option("-a", "--add-entry", dest="new_entry",
            action="store_true", default=False,
            help = "Add account(s). Optionally list new account names on the commandline.")

    parser.add_option("-d", "--delete-entry", dest="delete_entry",
            action = "store_true", default=False,
            help = "Specify account(s) to delete on commandline. Must match exactly.")

    parser.add_option("-k", "--keys", dest="print_keys",
            action = "store", type = "string",
            help = "Specify, in a comma-separated list (no spaces), which fields to print: i.e., custom1,custom2.\nUse --users and --passwords for non-custom fields.")

    parser.add_option('-f', '--password-file', dest = 'pass_file',
            action = 'store', type = 'string',
            help = "Specify a password file other than the default [~/.passwords.gpg].")

    parser.add_option("-C", "--config-file", dest="conf_file",
            action = "store", type = "string",
            help = "Specify a configuration file other than the default [~/.rpass.conf].")

    parser.add_option("-c", "--color", dest='color',
            action = "count", default = 0,
            help = "Enable color printing.")

    parser.add_option('--no-color', dest='no_color',
            action = "count", default = 0,
            help = "Disable color printing [default].")

    (options, args) = parser.parse_args()

    fops = {}
    if options.conf_file: fops['conf_file'] = options.conf_file
    else: fops['conf_file'] = '~/.rpass.conf'
    fops['batch'] = options.batch_mode
    if options.xclip > 0: fops['copy'] = True
    if options.no_xclip > 0: fops['copy'] = False
    if 'copy' not in fops: fops['copy'] = True
    fops['login'] = options.login
    fops['new_entry'] = options.new_entry
    fops['del_entry'] = options.delete_entry
    if options.color > 0: fops['color'] = True
    if options.no_color > 0: fops['color'] = False

    if options.print_keys == None: fops['fields'] = []
    elif options.print_keys.strip() == "": fops['fields'] = [None]
    else: fops['fields'] = [f.strip() for f in options.print_keys.split(',') if f.strip()]
    if options.print_users: fops['fields'].append('user')
    if options.print_pass: fops['fields'].extend(["pass"])

    if options.pass_file: 
        from os.path import expanduser
        fops['passfile'] = expanduser(options.pass_file)
    if 'passfile' not in fops: fops['passfile'] = None

    return (fops, args)

if __name__=="__main__":
    from rpass import rpass
    from rpass import InvalidEncryptionKey,ExistingEntry

    (options, args) = GetOptions()

    account = rpass(conf_file = options['conf_file'], passfile = options['passfile'], executable = True)

    if 'color' not in options:
        if 'color' in account.options:
            options['color'] = account.options['color']
        else: options['color'] = False

    if not(options['fields']):
        if 'fields' in account.options:
            options['fields'] = account.options['fields']
        else: options['fields'] = []

    if options['fields'] == [None]: options['fields'] = []

    if account.first:
        response = input("No password file at {0} found. Would you like to create it (note: please don't create this file manually)? [Y/n] ".format(account.passfile))

        if response != '' and response.lower()[0] == 'n':
            print("No password file created...Exiting.")
            exit()

        if options['new_entry'] and len(args) > 0:
            for arg in args: account.AddEntry(*CreateEntry(arg))
        else: account.AddEntry(*CreateEntry())

        account.Write()
        exit()

    if options['login']:
        try:
            account.DecryptPassFile(account.passfile)
            exit(0)
        except:
            print("Login failed.")
            exit(1)

    elif options['new_entry']:
        try:
            if len(args) > 0:
                for arg in args: account.AddEntry(*CreateEntry(arg))
            else: account.AddEntry(*CreateEntry())
            account.Write()
        except ExistingEntry:
            print("Entry exists...aborting addition.")

        exit()

    elif options['del_entry']:
        try:
            if len(args) > 0:
                for arg in args: account.DeleteEntry(entry = arg)
                account.Write()
            else: print ("Please specify entry or entries to delete.")
        except NonExistentEntry:
            print("One of your entries does not exist. Deleting operation aborted.")
        exit()

    else:
        acinfo = {}
        pfull = False

        if len(args) > 0:
            pfull = True
            for arg in args: 
                acinfo.update(account.GetAccountInfo(account = arg, strict = options['batch']))
            # Copy passwords...
            if not(options['batch']) and options['copy']:
                try:
                    account.CopyPass(acinfo=acinfo)
                except OSError:
                    print("'xclip' not found. Please install xclip to automatically copy first matched password to clipboard (avoid printing passwords).")
                    print("To see passwords, run rpass with the --passwords option.\n")
        else:
            acinfo = account.entries
        PrintAccountInfo(acinfo=acinfo, pfull = pfull, color = options['color'], keys = options['fields'], batch = options['batch'])
